version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:14.2.0
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
workflows:
    test:
      jobs:
        - test